set1 = set()

n = input("Enter number: ")
set1.add(int(n))
n = input("Enter number: ")
set1.add(int(n))
n = input("Enter number: ")
set1.add(int(n))
n = input("Enter number: ")
set1.add(int(n))
n = input("Enter number: ")
set1.add(int(n))
n = input("Enter number: ")
set1.add(int(n))
n = input("Enter number: ")
set1.add(int(n))
n = input("Enter number: ")
set1.add(int(n))

print(set1)